remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Project 4
description: In this project we worked with static data, gained experience writing and executing Node.js REST API server using VSCode. We also used Postman and fastify to test GET routes. Worked with JSON 
